const displayN = document.querySelector('#nameChar')
const displayH = document.querySelector('#heightChar')
const displayM = document.querySelector('#massChar')
const displayHC = document.querySelector('#hairColorChar')
const displaySC = document.querySelector('#skinColorChar')
const displayP = document.querySelector('#planet')
const displayN2 = document.querySelector('#nameChar2')
const displayH2 = document.querySelector('#heightChar2')
const displayM2 = document.querySelector('#massChar2')
const displayHC2 = document.querySelector('#hairColorChar2')
const displaySC2 = document.querySelector('#skinColorChar2')
const displayP2 = document.querySelector('#planet2')
const displayN3 = document.querySelector('#nameChar3')
const displayH3 = document.querySelector('#heightChar3')
const displayM3 = document.querySelector('#massChar3')
const displayHC3 = document.querySelector('#hairColorChar3')
const displaySC3 = document.querySelector('#skinColorChar3')
const displayP3 = document.querySelector('#planet3')
const displayN4 = document.querySelector('#nameChar4')
const displayH4 = document.querySelector('#heightChar4')
const displayM4 = document.querySelector('#massChar4')
const displayHC4 = document.querySelector('#hairColorChar4')
const displaySC4 = document.querySelector('#skinColorChar4')
const displayP4 = document.querySelector('#planet4')
const displayN5 = document.querySelector('#nameChar5')
const displayH5 = document.querySelector('#heightChar5')
const displayM5 = document.querySelector('#massChar5')
const displayHC5 = document.querySelector('#hairColorChar5')
const displaySC5 = document.querySelector('#skinColorChar5')
const displayP5 = document.querySelector('#planet5')
const displayN6 = document.querySelector('#nameChar6')
const displayH6 = document.querySelector('#heightChar6')
const displayM6 = document.querySelector('#massChar6')
const displayHC6 = document.querySelector('#hairColorChar6')
const displaySC6 = document.querySelector('#skinColorChar6')
const displayP6 = document.querySelector('#planet6')
function emptyCells(){
    displayN.innerText = ""
    displayH.innerText = ""
    displayM.innerText = ""
    displayHC.innerText = ""
    displaySC.innerText = ""
    displayP.innerText = ""
    displayN2.innerText = ""
    displayH2.innerText = ""
    displayM2.innerText = ""
    displayHC2.innerText = ""
    displaySC2.innerText = ""
    displayP2.innerText = ""
    displayN3.innerText = ""
    displayH3.innerText = ""
    displayM3.innerText = ""
    displayHC3.innerText =  ""
    displaySC3.innerText = ""
    displayP3.innerText = ""
    displayN4.innerText = ""
    displayH4.innerText = ""
    displayM4.innerText = ""
    displayHC4.innerText =  ""
    displaySC4.innerText = ""
    displayP4.innerText = ""
    displayN5.innerText = ""
    displayH5.innerText = ""
    displayM5.innerText = ""
    displayHC5.innerText =  ""
    displaySC5.innerText = ""
    displayP5.innerText = ""
    displayN6.innerText = ""
    displayH6.innerText = ""
    displayM6.innerText = ""
    displayHC6.innerText =  ""
    displaySC6.innerText = ""
    displayP6.innerText = ""
}

export {emptyCells}